### ISSUE TITLE
Services Module wouldn't work with Stage.PRODUCTION

### ISSUE THREAD

**Issue by mrserverless** [gwizard/gwizard#11]
Found this issue whilst I was trying to setup some auto registration for Services.

Basically if in any of the `ServiceModule` related tests, if you just modify the injector to be:

```
injector = Guice.createInjector(Stage.PRODUCTION, new ServicesModule());
```

This would result in all services being added to get error:

```
Error injecting constructor, java.lang.IllegalStateException: You can't add services after the system has started
```

The problem is caused by the assumption that `Services` is a lazy Singleton which is always initiated AFTER all the Services (in eager singleton scope) have been added. However, when the injector stage is set to `Stage.PRODUCTION`, the `Services` also becomes a eager singleton and starts up the `ServiceManager` right away. See https://github.com/google/guice/wiki/Scopes

I will create a PR for my Services auto registration code which includes tests illustrating what I mean.

**Comment by stickfigure** [comment]
Assuming this issue no longer relevant.
