### ISSUE TITLE
Swagger module not published to maven central

### ISSUE THREAD

**Issue by JLLeitschuh** [gwizard/gwizard#17]
I'd love to use the swagger module in my project but it's not published.
I built it by hand and installed it locally for now but this won't work once I upload my code to git to run on travis.

I can host it in my own personal jfrog artifactory but if you can publish it to m2 that would be helpful.

**Comment by JLLeitschuh** [comment]
Okay, this is proving to be a bit more difficult than I thought. There's really no good way to publish a snapshot to a private repository that is free for open source projects.
Would you be willing to publish a release with the swagger module to maven central?

**Comment by JLLeitschuh** [comment]
I found a solution with https://jitpack.io/

```groovy
compile group: 'com.github.gwizard.gwizard', name: 'gwizard-rest', version: gwizard_version
compile group: 'com.github.gwizard.gwizard', name: 'gwizard-logging', version: gwizard_version
compile (group: 'com.github.gwizard.gwizard', name: 'gwizard-swagger', version:
        gwizard_version) {
    exclude group: 'javax.servlet', module: 'servlet-api'
}
```

**Comment by lookfirst** [comment]
@JLLeitschuh neat solution for pushing jars... =)
