### ISSUE TITLE
Cannot handle sessions with the current configuration of the webserver

### ISSUE THREAD

**Issue by shudas** [gwizard/gwizard#20]
I tried to set up a custom WebServer implementation which uses a ServletContextHandler that can handle Sessions. I first tried to add the ServletContextHandler to the WebServer by overriding createServer and putting the logic there:

`Server server = super.createServer(webConfig);`
`new ServletContextHandler(server, "/*", ServletContextHandler.SESSIONS)`
`return server`

But I saw that the code in `WebServer::start` actually overwrites whatever I put on the server w/ it's own ServletContextHandler.

So then I tried binding my ServletContextHandler since the handlerScanner should pick it up, and it did get picked up. But it still did not work for me. Any calls `request.getSession()` resulted in errors in my logic. It threw
`IllegalStateException: No SessionManager`. I even added the GuiceFilter, DefaultServlet, and GuiceResteasyBootstrapServletContextListener to my custom ServletContextHandler (it essentially looked like the same ServletContextHandler that `WebServer::start` creates except that it is set up to handle sessions), and it still failed.

My workaround, which is horrendously ugly, was to copy all of the code in WebServer and change the `start` method from:
`final ServletContextHandler sch = new ServletContextHandler(server, "/");` to 
`final ServletContextHandler sch = new ServletContextHandler(server, "/", ServletContextHanlder.SESSIONS);`

I think this could be my lack of understanding of jetty server, servlet stuff, and I could be doing something wrong the first time around but given that it worked w/ my workaround, I am not sure if that is the case.

**Comment by stickfigure** [comment]
Can you submit a PR that would make it easier to intercept or configure this behavior? At simplest it could be a protected method that you can override in your own `WebServer` subclass.

**Comment by shudas** [comment]
Made the simple fix and verified that it works w/ a very simple test case by changing WebModuleExample

https://github.com/gwizard/gwizard/pull/21

**Comment by stickfigure** [comment]
PR applied and new release (0.8) is now in maven central. Thanks!
