### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by KamBha** [gwizard/gwizard#22]
This project has not gotten any love of late.  This could be a sign that it is stable (which would be great) or that this project has been abandoned.  I would like to know before pursuing its usage.

Thanks.

**Comment by stickfigure** [comment]
It's not abandoned, it's just pretty much "done". The idea was always to keep it as a minimal set of tools that you could wire together yourself with Guice. The documentation is longer than the code.

**Comment by JLLeitschuh** [comment]
It just doesn't get much action. If you find problems feel free to open issues and someone will try to get back to you.

**Comment by KamBha** [comment]
That is what I wanted to hear.  

Thanks.

K.
